#!/usr/bin/env bash

PID_FILE=/tmp/satallowance-pid

usage () {
    echo "Usage: satallowance help|start|stop|status"
}

error () {
    echo "Unknown command: $@"
    usage
}

start () {
    source env/bin/activate
    touch $PID_FILE
    python3 server.py & echo $! >> $PID_FILE
    python3 -m http.server 8000 & echo $! >> $PID_FILE
    python3 -m webbrowser http://localhost:8000
    deactivate
}

stop () {
    while read pid; do
        kill -9 $pid
    done <$PID_FILE
    rm $PID_FILE
}

status () {
    if [ -f $PID_FILE ]; then
        echo "Running."
    else
        echo "Stopped."
    fi
}

declare -A COMMANDS=(
    [error]=error
    [help]=usage
    [start]=start
    [stop]=stop
    [status]=status
)

# Magic line that makes it all working
"${COMMANDS[${1:-error}]:-${COMMANDS[error]}}" "$@"